---
- hosts: all
  tasks:
    - name: Install NodeJs
      ansible.builtin.package:
        state: present
        name: nodejs
      become: yes

    - name: Install NPM
      ansible.builtin.package:
        state: present
        name: npm
      become: yes

    - name: Install NPM packages
      ansible.builtin.command:
        chdir: ../../ui
        cmd: npm install

    - name: Build UI
      ansible.builtin.command:
        chdir: ../../ui
        cmd: npm run build

    - name: Copy Systemd Service
      ansible.builtin.template:
        src: ../service/partyq.service
        dest: /etc/systemd/system/partyq.service
        mode: '644'
        owner: root
        group: root
      become: yes

    - name: Stop PartyQ if currently running
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: partyq
        state: stopped
      become: yes
      ignore_errors: yes

    - name: Start PartyQ
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: started 
        name: partyq
      become: yes
