name: "Deploy PartyQ"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check active
        run: |
          pwd
          ls
          whoami
