name: "Deploy PartyQ"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start PartyQ
        run: |
          VENV=~/partyq
          pwd
          if [ ! -d  $VENV ]
          then
            python -m venv ~/partyq/
          fi
          sudo su
          source ~/partyq/bin/activate
          pip install --require-virtualenv -r requirements.txt
          ansible-playbook install/ansible/playbook.yml  --inventory 127.0.0.1, -l 127.0.0.1
