name: "Deploy PartyQ"
on:
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install PartyQ
        run: |
          pwd
          VENV=media/partyq
          if [ ! -d  $VENV ]
          then
            python -m venv $VENV
          fi
          source $VENV/bin/activate 
          pip install --require-virtualenv -r requirements.txt
          docker run --user -w /tmp/ui --volume  $(pwd)/ui:/tmp/ui node:20-alpine sh -c "npm install; npm run build; rm -rf node_modules"
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
            install/ansible/playbook.yml \
            --inventory 127.0.0.1, -l 127.0.0.1 \
            --connection local \
            -e "virtualenv=$VIRTUAL_ENV"
