name: "Deploy PartyQ"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start PartyQ
        run: |
          VENV=~/partyq
          pwd
          if [ ! -d  $VENV ]
          then
            python -m venv ~/partyq/
          fi
          sudo su
          source ~/partyq/bin/activate
          pip install --require-virtualenv -r requirements.txt
          
          export VIRTUAL_ENV=/opt/actions-runner/partyq 
          source ~/partyq/bin/activate && ./start.sh &
          echo $! > pid
