name: "Deploy PartyQ"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check active
        run: |
          VENV=~/partyq
          if [ ! -d  $VENV ]
          then
            python -m venv ~/partyq/
          fi
          source ~/partyq/bin/activate
          pip install -r requirements.txt
          
          # session=$(tmux ls | grep partyq)
          # if [ -n session ]
          # then
          #   tmux kill-session -t partyq
          # fi

          # tmux new-session -d -s partyq 'source ~/partyq/bin/activate && ./start.sh'
